### ISSUE TITLE
How to set custom alternate for neovim

### ISSUE THREAD

**Issue by lefuturiste** [rmagatti/alternate-toggler#6]
Hi!
Not a bug or anything, I'm trying to do everything with lua instead of vimscript.
I just want a equivalent of this statement in vimscript:
```
let g:at_custom_alternates = {'===': '!==', 'yes':'no'}
noremap <leader>ta :ToggleAlternate<CR>
```
in lua
I tried this:
```
vim.g.at_custom_alternates = {'===' = '!==', 'yes' = 'no'}
```
but It gave me a syntax error.

Any idea how this could work?

Thanks

**Comment by rmagatti** [comment]
Try this?
`vim.g.at_custom_alternates = {['==='] = '!==', ['yes'] = 'no'}`

**Comment by lefuturiste** [comment]
Thanks this worked as expected!
