### ISSUE TITLE
unsupported alternate value but configured in user defined table

### ISSUE THREAD

**Issue by juiceDeLemon** [rmagatti/alternate-toggler#9]
^title
config:
```
vim.api.nvim_set_var("at_custom_alternates", {
    ["=="] = "!=",
    ["==="] = "!==",
    ["yes"] = "no",
    ["on"] = "off",
    ["On"] = "Off",
    ["ON"] = "OFF",
    ["*"] = "/",
    ["++"] = "--",
    ["+="] = "-=",
    ["*="] = "/=",
    ["&"] = "|",
    ["&&"] = "||",
    ["define"] = "undef",
    [">="] = "<=",
})
```
Expected result:
```==``` changed to ```!=``` or any other custom-defined pairs in the above table.
Result:
```Unsupported alternate value.``` is printed.

I don't know if it is my code that is wrong because I'm relatively new to neovim's lua config and I couldn't get it to work using the ```vim.api()``` function. So you might need to check my code first.

**Comment by rmagatti** [comment]
Hey @juiceDeLemon. You could probably just use `vim.g` to set the global variable.
```lua
vim.g.at_custom_alternates = {
  ["=="] = "!="
  -- rest of your table
}
```

**Comment by juiceDeLemon** [comment]
fixed it using vim.g.at_custom_alternates
